import { invoke } from "@tauri-apps/api/core";

const KIND = { SUCCESS: "success", ERROR: "error" } as const;
const ERROR_CODE = { INVALID_RANGE: "invalid_range", SALE_NOT_FOUND: "sale_not_found", PERSISTENCE_FAILURE: "persistence_failure" } as const;
const PAYMENT_METHOD = { CASH: "cash", QR: "qr" } as const;
export type SalesLifecycleStatus = "confirmed" | "cancelled";
export interface SalesHistorySummary { sale_id: number; confirmed_at: string; status: SalesLifecycleStatus; total_centavos: number; line_count: number; payment_count: number; payment_methods: Array<(typeof PAYMENT_METHOD)[keyof typeof PAYMENT_METHOD]>; has_corrections: boolean; }
export interface HistoricalLine { sale_line_id: number; product_id: number; sku: string | null; product_name: string | null; quantity: number; unit_price_centavos: number; line_total_centavos: number; returned_quantity: number; cancellation_restored_quantity: number; remaining_returnable_quantity: number; }
export interface CashPayment { method: typeof PAYMENT_METHOD.CASH; amount_applied_centavos: number; amount_tendered_centavos: number; change_given_centavos: number; }
export interface QrPayment { method: typeof PAYMENT_METHOD.QR; amount_applied_centavos: number; }
export interface HistoricalReturnLine { sale_line_id: number; product_id: number; quantity: number; }
export interface HistoricalReturn { return_id: number; request_id: string; occurred_at: string; lines: HistoricalReturnLine[]; }
export interface HistoricalCancellationLine { sale_line_id: number; product_id: number; restored_quantity: number; }
export interface HistoricalCancellation { cancellation_id: number; request_id: string; occurred_at: string; reason: string; lines: HistoricalCancellationLine[]; }
export interface SalesHistoryDetail { sale_id: number; confirmed_at: string; status: SalesLifecycleStatus; total_centavos: number; lines: HistoricalLine[]; payments: Array<CashPayment | QrPayment>; returns: HistoricalReturn[]; cancellation: HistoricalCancellation | null; }
export interface SalesHistoryError { kind: typeof KIND.ERROR; code: (typeof ERROR_CODE)[keyof typeof ERROR_CODE]; message: string; }
export type SalesHistoryListResponse = { kind: typeof KIND.SUCCESS; sales: SalesHistorySummary[]; has_more: boolean } | SalesHistoryError;
export type SalesHistoryDetailResponse = { kind: typeof KIND.SUCCESS; detail: SalesHistoryDetail } | SalesHistoryError;
type Invoke = (command: string, payload: Record<string, unknown>) => Promise<unknown>;
type RecordValue = Record<string, unknown>;
type LocalMidnight = (year: number, month: number, day: number) => Date;
const record = (value: unknown): RecordValue | undefined => typeof value === "object" && value !== null ? value as RecordValue : undefined;
const failure = (): SalesHistoryError => ({ kind: KIND.ERROR, code: ERROR_CODE.PERSISTENCE_FAILURE, message: "Sales history could not be loaded." });
const localMidnight: LocalMidnight = (year, month, day) => new Date(year, month, day);
const validDate = (value: string): [number, number, number] => /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(new Date(`${value}T12:00:00`).getTime()) ? [Number(value.slice(0, 4)), Number(value.slice(5, 7)) - 1, Number(value.slice(8, 10))] : (() => { throw new Error("Dates must use YYYY-MM-DD."); })();
export function localDateRangeToUtc(from: string, to: string, makeLocalMidnight: LocalMidnight = localMidnight) { const [fromYear, fromMonth, fromDay] = validDate(from); const [toYear, toMonth, toDay] = validDate(to); const fromDate = makeLocalMidnight(fromYear, fromMonth, fromDay); const toDate = makeLocalMidnight(toYear, toMonth, toDay + 1); return { from_utc: fromDate.toISOString(), to_exclusive_utc: toDate.toISOString() }; }
const number = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value);
const string = (value: unknown): value is string => typeof value === "string";
const values = <Value>(value: unknown, decode: (item: unknown) => Value | undefined): Value[] | undefined => Array.isArray(value) ? (() => { const decoded = value.map(decode); return decoded.every((item): item is Value => item !== undefined) ? decoded : undefined; })() : undefined;
const summary = (value: unknown): SalesHistorySummary | undefined => { const item = record(value); const methods = item && values(item.payment_methods, value => value === "cash" || value === "qr" ? value : undefined); return item && methods && number(item.sale_id) && string(item.confirmed_at) && (item.status === "confirmed" || item.status === "cancelled") && number(item.total_centavos) && number(item.line_count) && number(item.payment_count) && typeof item.has_corrections === "boolean" ? { sale_id: item.sale_id, confirmed_at: item.confirmed_at, status: item.status, total_centavos: item.total_centavos, line_count: item.line_count, payment_count: item.payment_count, payment_methods: methods, has_corrections: item.has_corrections } : undefined; };
const line = (value: unknown): HistoricalLine | undefined => { const item = record(value); return item && number(item.sale_line_id) && number(item.product_id) && (item.sku === null || string(item.sku)) && (item.product_name === null || string(item.product_name)) && number(item.quantity) && number(item.unit_price_centavos) && number(item.line_total_centavos) && number(item.returned_quantity) && number(item.cancellation_restored_quantity) && number(item.remaining_returnable_quantity) ? { sale_line_id: item.sale_line_id, product_id: item.product_id, sku: item.sku, product_name: item.product_name, quantity: item.quantity, unit_price_centavos: item.unit_price_centavos, line_total_centavos: item.line_total_centavos, returned_quantity: item.returned_quantity, cancellation_restored_quantity: item.cancellation_restored_quantity, remaining_returnable_quantity: item.remaining_returnable_quantity } : undefined; };
const payment = (value: unknown): CashPayment | QrPayment | undefined => { const item = record(value); if (!item || !number(item.amount_applied_centavos)) return; if (item.method === "qr") return { method: "qr", amount_applied_centavos: item.amount_applied_centavos }; return item.method === "cash" && number(item.amount_tendered_centavos) && number(item.change_given_centavos) ? { method: "cash", amount_applied_centavos: item.amount_applied_centavos, amount_tendered_centavos: item.amount_tendered_centavos, change_given_centavos: item.change_given_centavos } : undefined; };
const returnLine = (value: unknown): HistoricalReturnLine | undefined => { const item = record(value); return item && number(item.sale_line_id) && number(item.product_id) && number(item.quantity) ? { sale_line_id: item.sale_line_id, product_id: item.product_id, quantity: item.quantity } : undefined; };
const returned = (value: unknown): HistoricalReturn | undefined => { const item = record(value); const lines = item && values(item.lines, returnLine); return item && lines && number(item.return_id) && string(item.request_id) && string(item.occurred_at) ? { return_id: item.return_id, request_id: item.request_id, occurred_at: item.occurred_at, lines } : undefined; };
const cancellationLine = (value: unknown): HistoricalCancellationLine | undefined => { const item = record(value); return item && number(item.sale_line_id) && number(item.product_id) && number(item.restored_quantity) ? { sale_line_id: item.sale_line_id, product_id: item.product_id, restored_quantity: item.restored_quantity } : undefined; };
const cancellation = (value: unknown): HistoricalCancellation | null | undefined => { if (value === null) return null; const item = record(value); const lines = item && values(item.lines, cancellationLine); return item && lines && number(item.cancellation_id) && string(item.request_id) && string(item.occurred_at) && string(item.reason) ? { cancellation_id: item.cancellation_id, request_id: item.request_id, occurred_at: item.occurred_at, reason: item.reason, lines } : undefined; };
const decodedDetail = (value: unknown): SalesHistoryDetail | undefined => { const item = record(value); const lines = item && values(item.lines, line); const payments = item && values(item.payments, payment); const returns = item && values(item.returns, returned); const cancelled = item && cancellation(item.cancellation); return item && lines && payments && returns && cancelled !== undefined && number(item.sale_id) && string(item.confirmed_at) && (item.status === "confirmed" || item.status === "cancelled") && number(item.total_centavos) ? { sale_id: item.sale_id, confirmed_at: item.confirmed_at, status: item.status, total_centavos: item.total_centavos, lines, payments, returns, cancellation: cancelled } : undefined; };
const error = (value: RecordValue): SalesHistoryError => string(value.code) && Object.values(ERROR_CODE).includes(value.code as SalesHistoryError["code"]) ? { kind: KIND.ERROR, code: value.code as SalesHistoryError["code"], message: string(value.message) ? value.message : failure().message } : failure();
const list = (value: unknown): SalesHistoryListResponse => { const response = record(value); if (!response) return failure(); if (response.kind === KIND.ERROR) return error(response); const sales = values(response.sales, summary); return response.kind === KIND.SUCCESS && sales && typeof response.has_more === "boolean" ? { kind: KIND.SUCCESS, sales, has_more: response.has_more } : failure(); };
const detail = (value: unknown): SalesHistoryDetailResponse => { const response = record(value); if (!response) return failure(); if (response.kind === KIND.ERROR) return error(response); const decoded = decodedDetail(response.detail); return response.kind === KIND.SUCCESS && decoded ? { kind: KIND.SUCCESS, detail: decoded } : failure(); };
export function createSalesHistoryCommands(command: Invoke) { return { list: (from: string, to: string) => command("list_sales_history_command", { request: localDateRangeToUtc(from, to) }).then(list).catch(failure), detail: (saleId: number) => command("sale_history_detail_command", { saleId }).then(detail).catch(failure) }; }
export const salesHistoryCommands = createSalesHistoryCommands(invoke as Invoke);
