import { createElement, type ChangeEvent, type FormEvent, useEffect, useReducer, useState } from "react";

import { ATTRIBUTE_FIELD_TYPE, CATALOG_INTENT, catalogMaintenanceCommands, type CatalogMaintenanceRecord, type CatalogMetadataDetail } from "../../commands/catalog.ts";
import { createCatalogEditRequest, createCatalogMaintenanceFlow, fieldErrorsForCatalogEdit, formForCatalogDetail, initialCatalogMaintenanceState, type CatalogEditFieldErrors, type CatalogEditForm, type CatalogMaintenanceAction } from "./catalog-maintenance-flow.ts";

type Dispatch = (action: CatalogMaintenanceAction) => void;
type SetForm = (form: CatalogEditForm) => void;
type CatalogLoadCommands = Pick<typeof catalogMaintenanceCommands, "detail" | "list">;
export function CatalogMaintenanceRecovery({ required, onReload }: { required: boolean; onReload: () => void }) { return required ? createElement("button", { type: "button", onClick: onReload }, "Reload catalog records") : null; }
export function CatalogSuccessNotice({ notice }: { notice: string | null }) { return notice ? createElement("p", { role: "status" }, notice) : null; }
export async function loadCatalogRecords(commands: CatalogLoadCommands, dispatch: Dispatch) { dispatch({ type: "load_started" }); const response = await commands.list(); dispatch(response.kind === "success" ? { type: "loaded", records: response.records } : { type: "load_failed" }); }
export async function loadCatalogDetail(commands: CatalogLoadCommands, dispatch: Dispatch, setForm: SetForm, record: CatalogMaintenanceRecord) { dispatch({ type: "detail_started", record }); const response = await commands.detail(record); if (response.kind === "success") { setForm(formForCatalogDetail(response.detail)); dispatch({ type: "detail_loaded", detail: response.detail }); } else dispatch({ type: "detail_failed", code: response.code }); }
export async function reloadCatalogRecords(commands: CatalogLoadCommands, dispatch: Dispatch, setForm: SetForm, selected: CatalogMaintenanceRecord | null) { await loadCatalogRecords(commands, dispatch); if (selected) await loadCatalogDetail(commands, dispatch, setForm, selected); }
interface CatalogMetadataEditorProps { detail: CatalogMetadataDetail; form: CatalogEditForm; pending: boolean; feedback: string | null; fieldErrors: CatalogEditFieldErrors; onChange: (field: string, value: string) => void; onSubmit: () => void; }
export function CatalogMetadataEditor({ detail, form, pending, feedback, fieldErrors, onChange, onSubmit }: CatalogMetadataEditorProps) {
  const invalid = (field: string) => fieldErrors[field] ? { "aria-invalid": true, "aria-describedby": `catalog-edit-${field}-error` } : {};
  const error = (field: string) => fieldErrors[field] ? createElement("p", { id: `catalog-edit-${field}-error`, role: "alert" }, fieldErrors[field]) : null;
  const attribute = (definition: CatalogMetadataDetail["attribute_definitions"][number]) => { const field = `attribute-${definition.definition_id}`; return createElement("label", { key: definition.definition_id, htmlFor: `catalog-${field}` }, `${definition.label}${definition.required ? " (required)" : ""}`, definition.field_type === ATTRIBUTE_FIELD_TYPE.OPTION ? createElement("select", { id: `catalog-${field}`, required: definition.required, disabled: pending, ...invalid(field), value: form.attribute_values[definition.definition_id] ?? "", onChange: (event: ChangeEvent<HTMLSelectElement>) => onChange(field, event.target.value) }, createElement("option", { value: "" }, "Select"), definition.options.map((option) => createElement("option", { key: option, value: option }, option))) : createElement("input", { id: `catalog-${field}`, type: definition.field_type === ATTRIBUTE_FIELD_TYPE.NUMBER ? "number" : "text", step: definition.field_type === ATTRIBUTE_FIELD_TYPE.NUMBER ? "any" : undefined, required: definition.required, disabled: pending, ...invalid(field), value: form.attribute_values[definition.definition_id] ?? "", onChange: (event: ChangeEvent<HTMLInputElement>) => onChange(field, event.target.value) }), error(field)); };
  return createElement("form", { onSubmit: (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSubmit(); }, "aria-busy": pending }, createElement("h2", null, detail.target === "category" ? "Edit category" : "Edit product"), detail.activity === "archived" ? createElement("p", null, "Archived record. Editing metadata does not reactivate it.") : null, createElement("label", { htmlFor: "catalog-edit-name" }, detail.target === "category" ? "Category name" : "Product name"), createElement("input", { id: "catalog-edit-name", required: true, disabled: pending, ...invalid("name"), value: form.name, onChange: (event: ChangeEvent<HTMLInputElement>) => onChange("name", event.target.value) }), error("name"), detail.target === "product" ? createElement("fieldset", null, createElement("legend", null, "Product details"), createElement("label", { htmlFor: "catalog-edit-sku" }, "SKU"), createElement("input", { id: "catalog-edit-sku", required: true, disabled: pending, ...invalid("sku"), value: form.sku ?? "", onChange: (event: ChangeEvent<HTMLInputElement>) => onChange("sku", event.target.value) }), error("sku"), createElement("label", { htmlFor: "catalog-edit-price" }, "Current catalog price (centavos; affects future sales only)"), createElement("input", { id: "catalog-edit-price", type: "number", min: 1, step: 1, required: true, disabled: pending, ...invalid("catalog_unit_price_centavos"), value: form.catalog_unit_price_centavos ?? "", onChange: (event: ChangeEvent<HTMLInputElement>) => onChange("catalog_unit_price_centavos", event.target.value) }), error("catalog_unit_price_centavos"), createElement("p", null, "Confirmed sale prices are historical and unchanged."), detail.attribute_definitions.map(attribute)) : null, feedback ? createElement("p", { id: "catalog-edit-feedback", role: "alert" }, feedback) : null, createElement("button", { type: "submit", disabled: pending }, pending ? "Saving catalog metadata…" : "Save catalog metadata"));
}
export function CatalogMaintenanceScreen() {
  const [state, dispatch] = useReducer(createCatalogMaintenanceFlow, initialCatalogMaintenanceState);
  const [form, setForm] = useState<CatalogEditForm | null>(null);
  const load = () => loadCatalogRecords(catalogMaintenanceCommands, dispatch);
  const loadDetail = (record: CatalogMaintenanceRecord) => loadCatalogDetail(catalogMaintenanceCommands, dispatch, setForm, record);
  useEffect(() => { void load(); }, []);
  const maintain = async (record: CatalogMaintenanceRecord) => { dispatch({ type: "mutation_started" }); const response = await catalogMaintenanceCommands.maintain({ target: record.target, entity_id: record.entity_id, intent: record.activity === "active" ? CATALOG_INTENT.ARCHIVE : CATALOG_INTENT.REACTIVATE, expected_revision: record.revision }); dispatch(response.kind === "success" ? { type: "mutation_succeeded", record: response } : { type: "mutation_failed", code: response.code }); };
  const edit = async () => { if (!state.detail || !form) return; const errors = fieldErrorsForCatalogEdit(state.detail, form); const request = createCatalogEditRequest(state.detail, form); if (!request) { dispatch({ type: "edit_validation_failed", field_errors: errors }); return; } dispatch({ type: "edit_started" }); const response = await catalogMaintenanceCommands.edit(request); if (response.kind === "error") { dispatch({ type: "edit_failed", code: response.code }); return; } dispatch({ type: "edit_succeeded" }); await load(); await loadDetail({ target: response.target, entity_id: response.entity_id, label: "", activity: response.activity, revision: response.revision }); };
  const reload = () => reloadCatalogRecords(catalogMaintenanceCommands, dispatch, setForm, state.selected);
  const change = (field: string, value: string) => setForm((current) => !current ? current : field.startsWith("attribute-") ? { ...current, attribute_values: { ...current.attribute_values, [Number(field.slice(10))]: value } } : { ...current, [field]: value });
  return createElement("main", { "aria-labelledby": "catalog-maintenance-heading" }, createElement("h1", { id: "catalog-maintenance-heading" }, "Catalog maintenance"), createElement("p", null, "Edit metadata or archive and reactivate catalog categories and products."), createElement(CatalogSuccessNotice, { notice: state.success_notice }), state.status === "loading" ? createElement("p", { role: "status" }, "Loading catalog maintenance records…") : null, state.status === "unavailable" ? createElement("button", { type: "button", onClick: () => void reload() }, "Retry catalog maintenance") : null, createElement(CatalogMaintenanceRecovery, { required: state.recovery_required, onReload: () => void reload() }), createElement("ul", { "aria-label": "Catalog maintenance records" }, state.records.map((record) => createElement("li", { key: `${record.target}-${record.entity_id}` }, createElement("button", { type: "button", onClick: () => void loadDetail(record), disabled: state.status === "pending" }, `Details: ${record.label} (${record.target}, ${record.activity})`), createElement("button", { type: "button", disabled: state.status === "pending", onClick: () => void maintain(record) }, record.activity === "active" ? "Archive" : "Reactivate")))), state.detail && form ? createElement(CatalogMetadataEditor, { detail: state.detail, form, pending: state.status === "pending", feedback: state.feedback, fieldErrors: state.field_errors, onChange: change, onSubmit: () => void edit() }) : null, state.feedback && !state.detail ? createElement("p", { role: "alert" }, state.feedback) : null);
}
