import type { CatalogMaintenanceError, CatalogMaintenanceRecord } from "../../commands/catalog.ts";

const STATUS = { LOADING: "loading", READY: "ready", PENDING: "pending", UNAVAILABLE: "unavailable" } as const;
export interface CatalogMaintenanceState { status: (typeof STATUS)[keyof typeof STATUS]; records: CatalogMaintenanceRecord[]; feedback: string | null; recovery_required: boolean; }
export const initialCatalogMaintenanceState: CatalogMaintenanceState = { status: STATUS.LOADING, records: [], feedback: null, recovery_required: false };
export type CatalogMaintenanceAction = { type: "load_started" } | { type: "loaded"; records: CatalogMaintenanceRecord[] } | { type: "load_failed" } | { type: "mutation_started" } | { type: "mutation_succeeded"; record: CatalogMaintenanceRecord } | { type: "mutation_failed"; code: CatalogMaintenanceError["code"] };
const message = (code: CatalogMaintenanceError["code"]) => code === "validation_error" ? "Review the catalog values and try again." : code === "stale_catalog_record" ? "This catalog record changed. Reload and try again." : code === "lifecycle_blocked" ? "This lifecycle change is not allowed." : "The catalog change could not be completed.";
export function createCatalogMaintenanceFlow(state: CatalogMaintenanceState, action: CatalogMaintenanceAction): CatalogMaintenanceState {
  switch (action.type) { case "load_started": return { ...state, status: STATUS.LOADING, feedback: null, recovery_required: false }; case "loaded": return { status: STATUS.READY, records: action.records, feedback: null, recovery_required: false }; case "load_failed": return { ...state, status: STATUS.UNAVAILABLE, feedback: "Catalog maintenance is unavailable. Try again.", recovery_required: false }; case "mutation_started": return { ...state, status: STATUS.PENDING, feedback: null, recovery_required: false }; case "mutation_succeeded": return { status: STATUS.READY, feedback: "Catalog updated.", recovery_required: false, records: state.records.map((record) => record.entity_id === action.record.entity_id && record.target === action.record.target ? { ...record, activity: action.record.activity, revision: action.record.revision } : record) }; case "mutation_failed": return { ...state, status: STATUS.READY, feedback: message(action.code), recovery_required: action.code === "stale_catalog_record" }; }
}
